name = "cloudflare-d1-backups-example"
main = "src/index.ts"
compatibility_date = "2023-04-07"
usage_model = "bundled"
node_compat = true

[triggers]
crons = [ "0 * * * *" ]

[[ d1_databases ]]
binding = "DATABASE"
database_name = "ridetracker-staging"
database_id = "fc97d7d6-9958-4d2c-81d8-6fb6522cd862"

[[ r2_buckets ]]
binding = "BUCKET"
bucket_name = "ridetracker-staging"
